using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using NpgsqlTypes;
namespace Atlas;

public class Queries(AtlasDb db)
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public async Task<T> Read<T>(string sql, params object?[] values) { var args = values.Select((v, i) => v is null ? new NpgsqlParameter("p" + i, NpgsqlDbType.Text) { Value = DBNull.Value } : new NpgsqlParameter("p" + i, v)).Cast<object>().ToArray(); var rows = await db.Database.SqlQueryRaw<string>(sql, args).ToListAsync(); if (rows.Count == 0) throw new ApiFailure(404, "NOT_FOUND", "No matching published record"); return JsonSerializer.Deserialize<T>(rows[0], Json)!; }
    public async Task<Release> Select(QueryFilters q) { if (q.Mode is not ("demo" or "verified_historical")) throw new ApiFailure(400, "INVALID_MODE", "Choose verified_historical or demo"); if (!Rules.ValidYear(q.ProgramYear)) throw new ApiFailure(400, "INVALID_YEAR", "Use a consecutive program year, for example 2025-26"); if (q.Locale is not ("zh" or "en")) throw new ApiFailure(400, "INVALID_LOCALE", "Use zh or en"); Rules.ScopeAllowed(q.VisaSubclass, q.SponsorshipType); return await Read<Release>("SELECT jsonb_build_object('key',key,'mode',mode,'status',status)::text AS \"Value\" FROM dataset_version WHERE status='published' AND mode={0} AND ({1}::text IS NULL OR key={1}) ORDER BY published_at DESC,key DESC LIMIT 1", q.Mode, q.DatasetVersion); }
    public static void State(string state) { if (!Rules.Names.ContainsKey(state)) throw new ApiFailure(400, "INVALID_STATE", "Unknown state or territory"); }
    public async Task<Envelope<T>> Wrap<T>(T data, Release r, string coverage = "partial", params string[] warnings) where T : notnull { var citations = await Read<List<Citation>>("SELECT COALESCE(jsonb_agg(jsonb_build_object('sourceId',s.source_id,'sourceVersionId',s.id,'title',s.title,'publisher',s.publisher,'url',s.url,'locator',s.storage_key,'retrievedAt',s.retrieved_at,'publishedAt',s.published_at,'isDemo',s.is_demo) ORDER BY s.id),'[]'::jsonb)::text AS \"Value\" FROM source_version s JOIN dataset_source m ON m.source_version_id=s.id WHERE m.version={0}", r.Key); return new(data, new(r.Key, r.Mode == "demo", DateTimeOffset.UtcNow.ToString("O"), coverage, "Allocations, nomination invitations, visa invitations and EOI stock are distinct metrics."), citations, warnings.Concat(r.Mode == "demo" ? ["Synthetic demo data; not official history."] : Array.Empty<string>()).ToArray()); }
    const string FactJson = "jsonb_build_object('id',f.id,'metricType',f.metric_type,'value',f.value,'unit',f.unit,'status',f.status,'nullReason',f.null_reason,'programYear',s.program_year,'visaSubclass',s.visa_subclass,'eventDate',f.event_date,'periodStart',f.period_start,'periodEnd',f.period_end,'pointsBasis',s.points_basis,'occupationId',f.occupation_id,'sourceVersionId',f.source_version_id,'locator',f.locator,'eoiEffectiveAt',f.eoi_effective_at,'state',s.state,'stream',s.stream,'residenceCategory',s.residence_category,'classificationVersion',s.classification_version,'roundId',s.round_id,'asOfDate',f.as_of_date)";
    const string FactFrom = " FROM observation_revision f JOIN dataset_observation m ON m.observation_id=f.id JOIN program_scope s ON s.id=f.scope_id ";
    public async Task<List<MetricValue>> Facts(Release r, string state, string year, string? visa = null, string? occupation = null) => await Read<List<MetricValue>>("SELECT COALESCE(jsonb_agg(" + FactJson + " ORDER BY s.visa_subclass,f.metric_type,f.id),'[]'::jsonb)::text AS \"Value\"" + FactFrom + "WHERE m.version={0} AND s.state={1} AND s.program_year={2} AND ({3}::text IS NULL OR s.visa_subclass={3}) AND ({4}::text IS NULL OR f.occupation_id={4})", r.Key, state, year, visa, occupation);
    public async Task<Envelope<StatesData>> States(QueryFilters q) { var r = await Select(q); var items = await Read<List<StateSummary>>("SELECT jsonb_agg(x ORDER BY x->>'code')::text AS \"Value\" FROM (SELECT jsonb_build_object('code',j.code,'nameEn',j.name_en,'nameZh',j.name_zh,'coverageStatus',CASE WHEN {0}='demo' THEN 'synthetic' ELSE 'allocations_only' END,'allocation190',(SELECT f.value " + FactFrom + "WHERE m.version={1} AND s.state=j.code AND s.program_year={2} AND s.visa_subclass='190' AND f.metric_type='nomination_allocation'),'allocation491',(SELECT f.value " + FactFrom + "WHERE m.version={1} AND s.state=j.code AND s.program_year={2} AND s.visa_subclass='491' AND f.metric_type='nomination_allocation'),'publishedOccupationObservations',(SELECT count(*) " + FactFrom + "WHERE m.version={1} AND s.state=j.code AND s.program_year={2} AND f.metric_type='last_invited_eoi_points')) x FROM jurisdiction j) t", q.Mode, r.Key, q.ProgramYear); var years = await Read<List<string>>("SELECT COALESCE(jsonb_agg(y ORDER BY y DESC),'[]'::jsonb)::text AS \"Value\" FROM (SELECT DISTINCT s.program_year y " + FactFrom + "WHERE m.version={0}) t", r.Key); var versions = await Read<List<string>>("SELECT jsonb_agg(key ORDER BY key DESC)::text AS \"Value\" FROM dataset_version WHERE mode={0} AND status='published'", q.Mode); return await Wrap(new StatesData(items, years, versions), r); }
    public async Task<Envelope<StateOverview>> Overview(string state, QueryFilters q) { State(state); var r = await Select(q); var facts = await Facts(r, state, q.ProgramYear); var scopes = await Scopes(r, state, q); return await Wrap(new StateOverview(state, Rules.Names[state].En, Rules.Names[state].Zh, "not_ingested", "政策原文尚未录入；不据配额推断州政策。", facts.Where(f => f.MetricType == "nomination_allocation" && f.VisaSubclass == q.VisaSubclass).ToArray(), scopes, ["190", "491"]), r); }
    public async Task<List<ScopeChoice>> Scopes(Release r, string state, QueryFilters q) => await Read<List<ScopeChoice>>("SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'roundId',round_id,'stream',stream,'residenceCategory',residence_category,'pointsBasis',points_basis,'classificationVersion',classification_version,'eventDate',event_date) ORDER BY event_date),'[]'::jsonb)::text AS \"Value\" FROM program_scope WHERE id IN(SELECT s.id " + FactFrom + "WHERE m.version={0} AND s.state={1} AND s.program_year={2} AND s.visa_subclass={3} AND f.metric_type='last_invited_eoi_points')", r.Key, state, q.ProgramYear, q.VisaSubclass);
    public async Task<Envelope<List<MetricValue>>> Observations(string state, QueryFilters q) { State(state); var r = await Select(q); return await Wrap(await Facts(r, state, q.ProgramYear, q.VisaSubclass), r); }
    public async Task<Envelope<TopData>> Top(string state, QueryFilters q, string metric, int limit)
    {
        State(state); var r = await Select(q); if (metric is not ("last_invited_eoi_points" or "nomination_invitation_count")) throw new ApiFailure(400, "INVALID_METRIC", "Only nomination invitations or published last-invited EOI points are ranked"); if (limit < 1 || limit > 20) throw new ApiFailure(400, "INVALID_LIMIT", "Limit must be 1–20"); var scopes = await Scopes(r, state, q); if (scopes.Count == 0) return await Wrap(new TopData("not_ingested", "No comparable occupation round", metric, [], 0, 0, "No occupation-round evidence ingested for this scope"), r); if (q.RoundId is null || q.Stream is null || q.ResidenceCategory is null) throw new ApiFailure(422, "SCOPE_CONFIRMATION_REQUIRED", "Confirm one round, stream and residence category", scopes); var matches = scopes.Where(s => s.RoundId == q.RoundId && s.Stream == q.Stream && s.ResidenceCategory == q.ResidenceCategory).ToArray(); if (matches.Length != 1) throw new ApiFailure(409, "INCOMPARABLE_SCOPE", "Selected round and filters are not a single comparable group", scopes);
        var ranked = "WITH ranking AS(SELECT o.id occupation_id,o.code,o.title,o.title_zh,f.value,f.source_version_id,f.locator,f.eoi_effective_at,DENSE_RANK() OVER(ORDER BY f.value " + (metric == "last_invited_eoi_points" ? "ASC" : "DESC") + ") rank,ROW_NUMBER() OVER(ORDER BY f.value " + (metric == "last_invited_eoi_points" ? "ASC" : "DESC") + ",o.code) position" + FactFrom + "JOIN occupation o ON o.id=f.occupation_id WHERE m.version={0} AND s.id={1} AND f.metric_type={2} AND f.status='available') ";
        var items = await Read<List<RankedItem>>(ranked + "SELECT COALESCE(jsonb_agg(jsonb_build_object('occupationId',occupation_id,'code',code,'title',title,'titleZh',title_zh,'value',value,'rank',rank,'sourceVersionId',source_version_id,'locator',locator,'eoiEffectiveAt',eoi_effective_at) ORDER BY position),'[]'::jsonb)::text AS \"Value\" FROM ranking WHERE position<={3}", r.Key, matches[0].Id, metric, limit);
        var counts = await Read<JsonElement>(ranked + "SELECT jsonb_build_object('n',count(*),'tie',(SELECT count(*) FROM ranking WHERE value=(SELECT value FROM ranking WHERE position={3})) )::text AS \"Value\" FROM ranking", r.Key, matches[0].Id, metric, limit); return await Wrap(new TopData(items.Count > 0 ? "available" : "not_published", metric == "last_invited_eoi_points" ? "Published last-invited EOI points (lowest first)" : "Published nomination invitations (highest first)", metric, items, counts.GetProperty("tie").GetInt32(), counts.GetProperty("n").GetInt32(), null), r, "partial", "A last-invited score is not a guaranteed cutoff or success probability; ties at the boundary can be truncated by the display limit.");
    }
    const string OccJson = "jsonb_build_object('id',id,'system',system,'version',version,'code',code,'title',title,'titleZh',title_zh)";
    public async Task<List<OccupationSummary>> Catalog() => await Read<List<OccupationSummary>>("SELECT jsonb_agg(" + OccJson + " ORDER BY code)::text AS \"Value\" FROM occupation");
    public async Task<Envelope<List<OccupationSummary>>> Search(string text, QueryFilters q) { if (text.Length is < 1 or > 120) throw new ApiFailure(400, "INVALID_SEARCH", "Search length must be 1–120"); var r = await Select(q); var normalized = Rules.Normalize(text); var items = (await Catalog()).Where(o => Rules.Normalize(o.Title).Contains(normalized) || Rules.Normalize(o.TitleZh).Contains(normalized) || o.Code == normalized || normalized == "tiler" && o.Code == "333411" || normalized == "程序员" && o.Code.StartsWith("2613")).ToArray(); return await Wrap(items.ToList(), r, "catalog_only", "Occupation names are a curated catalog, not evidence of eligibility or invitations."); }
    public async Task<Envelope<OccupationData>> Occupation(string id, string state, QueryFilters q) { State(state); var r = await Select(q); var o = (await Catalog()).FirstOrDefault(x => x.Id == id) ?? throw new ApiFailure(404, "OCCUPATION_NOT_FOUND", "Confirm occupation code and classification version"); var facts = await Facts(r, state, q.ProgramYear, q.VisaSubclass, id); return await Wrap(new OccupationData(o, facts, facts.Count > 0 ? "available" : "not_ingested"), r); }
    public async Task<Envelope<DistributionData>> Distribution(string id, string state, QueryFilters q)
    {
        State(state); var r = await Select(q); var rows = await Read<List<JsonElement>>("SELECT COALESCE(jsonb_agg(to_jsonb(d)),'[]'::jsonb)::text AS \"Value\" FROM distribution d JOIN program_scope s ON s.id=d.scope_id WHERE d.version={0} AND d.occupation_id={1} AND s.state={2} AND s.visa_subclass={3} AND s.program_year={4}", r.Key, id, state, q.VisaSubclass, q.ProgramYear); if (rows.Count == 0) return await Wrap(new DistributionData("not_ingested", false, null, "Unknown", "unknown", "No score distribution ingested", []), r); if (rows.Count != 1) throw new ApiFailure(409, "DISTRIBUTION_SCOPE_REQUIRED", "Confirm exactly one distribution cohort"); var d = rows[0]; var did = d.GetProperty("id").GetString()!; long? denominator = d.GetProperty("denominator").ValueKind == JsonValueKind.Null ? null : d.GetProperty("denominator").GetInt64(); var kind = d.GetProperty("cohort_kind").GetString()!;
        var valid = await Read<JsonElement>("SELECT jsonb_build_object('n',count(*),'sum',sum(count),'missing',count(*) FILTER(WHERE status<>'available'),'overlap',EXISTS(SELECT FROM distribution_bin a JOIN distribution_bin b ON a.distribution_id=b.distribution_id AND a.id<b.id WHERE a.distribution_id={0} AND (a.lower<b.upper OR a.lower=b.upper AND a.lower_inclusive AND b.upper_inclusive) AND (b.lower<a.upper OR b.lower=a.upper AND b.lower_inclusive AND a.upper_inclusive)))::text AS \"Value\" FROM distribution_bin WHERE distribution_id={0}", did);
        bool chart = denominator > 0 && kind is "published_sample" or "full_cohort" or "eoi_stock" && valid.GetProperty("n").GetInt32() > 0 && valid.GetProperty("missing").GetInt32() == 0 && !valid.GetProperty("overlap").GetBoolean() && valid.GetProperty("sum").GetInt64() == denominator;
        var bins = await Read<List<PercentageRow>>("SELECT COALESCE(jsonb_agg(jsonb_build_object('lower',lower,'upper',upper,'count',count,'status',status,'percentage',CASE WHEN {1} THEN round(count*100.0/{2}::numeric,2) ELSE NULL END) ORDER BY lower),'[]'::jsonb)::text AS \"Value\" FROM distribution_bin WHERE distribution_id={0}", did, chart, denominator ?? 1); return await Wrap(new DistributionData(chart ? "available" : kind == "last_invited" ? "not_applicable" : "incomplete", chart, denominator, d.GetProperty("definition").GetString()!, kind, chart ? "Complete non-overlapping published sample; percentages are descriptive only" : kind == "last_invited" ? "A last-invited score does not define a score distribution" : "Denominator unknown, suppressed/missing bins, or overlapping bins; percentages withheld", bins), r);
    }
    public async Task<Envelope<TrendData>> Trend(string id, string state, QueryFilters q, string metric)
    {
        State(state); var r = await Select(q); if (metric is not ("nomination_invitation_count" or "visa_invitation_count")) throw new ApiFailure(400, "INVALID_TREND_METRIC", "Annual trends require a flow count; EOI stock and points cannot be summed");
        var baseSql = FactFrom + "WHERE m.version={0} AND s.state={1} AND s.visa_subclass={2} AND f.occupation_id={3} AND f.metric_type={4} AND f.status='available' AND f.period_start IS NOT NULL AND f.period_end IS NOT NULL AND s.round_id IS NULL";
        var periods = await Read<List<MetricValue>>("SELECT COALESCE(jsonb_agg(" + FactJson + "),'[]'::jsonb)::text AS \"Value\"" + baseSql, r.Key, state, q.VisaSubclass, id, metric); if (periods.Count == 0) return await Wrap(new TrendData("not_ingested", metric, "count", [], "No non-overlapping annual flow series ingested"), r);
        if (periods.Select(f => $"{f.Stream}:{f.ResidenceCategory}:{f.ClassificationVersion}:{f.PointsBasis}:{f.Unit}").Distinct().Count() != 1 || periods.Any(a => periods.Any(b => a.Id != b.Id && string.CompareOrdinal(a.PeriodStart, b.PeriodEnd) <= 0 && string.CompareOrdinal(b.PeriodStart, a.PeriodEnd) <= 0))) throw new ApiFailure(409, "INCOMPARABLE_PERIODS", "Annual aggregation requires comparable, non-overlapping periods");
        var points = await Read<List<TrendPoint>>("SELECT jsonb_agg(x ORDER BY x->>'programYear')::text AS \"Value\" FROM(SELECT jsonb_build_object('programYear',s.program_year,'value',sum(f.value),'periodEnd',max(f.period_end),'isYtd',(max(f.period_end)<make_date(left(s.program_year,4)::int+1,6,30) OR min(f.period_start)>make_date(left(s.program_year,4)::int,7,1) OR sum(f.period_end-f.period_start+1)<make_date(left(s.program_year,4)::int+1,6,30)-make_date(left(s.program_year,4)::int,7,1)+1)) x" + baseSql + " GROUP BY s.program_year) t", r.Key, state, q.VisaSubclass, id, metric); return await Wrap(new TrendData("available", metric, "count", points, "YTD is displayed separately; no year-on-year comparison with full years"), r);
    }
    public async Task<Envelope<SourceData>> Source(string source, string version, QueryFilters q) { var r = await Select(q); var result = await Read<SourceData>("SELECT jsonb_build_object('sourceId',s.source_id,'sourceVersionId',s.id,'title',s.title,'publisher',s.publisher,'url',s.url,'termsUrl',s.terms_url,'license',s.license,'hash',s.hash,'retrievedAt',s.retrieved_at,'publishedAt',s.published_at,'effectiveDate',s.effective_date,'decisionDate',s.decision_date,'snapshotScope',s.storage_key,'reviewNote',s.review_note,'datasetVersions',(SELECT jsonb_agg(version ORDER BY version) FROM dataset_source WHERE source_version_id=s.id))::text AS \"Value\" FROM source_version s JOIN dataset_source m ON m.source_version_id=s.id WHERE s.source_id={0} AND s.id={1} AND m.version={2} AND s.is_demo={3}", source, version, r.Key, r.Mode == "demo"); return await Wrap(result, r, "source_record"); }
    public async Task<Envelope<Interpretation>> Interpret(InterpretRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Text) || request.Text.Length > 1200) throw new ApiFailure(400, "INVALID_QUESTION", "Question length must be 1–1200"); var r = await Select(new(Mode: request.Mode, Locale: request.Locale)); var text = request.Text; var n = Rules.Normalize(text); var candidates = (await Catalog()).Where(o => n.Contains(Rules.Normalize(o.Title)) || n.Contains(o.TitleZh) || text.Contains(o.Code)).ToList(); if (candidates.Count == 0) { if (n.Contains("工程师") || n.Contains("engineer")) candidates = (await Catalog()).Where(o => o.Code is "261313" or "233211").ToList(); else if (n.Contains("程序员") || n.Contains("programmer")) candidates = (await Catalog()).Where(o => o.Code is "261312" or "261311").ToList(); else if (n.Contains("瓷砖") || n.Contains("tiler")) candidates = (await Catalog()).Where(o => o.Code == "333411").ToList(); }
        var states = Rules.StateCodes.Where(c => Regex.IsMatch(text, @"(?<![A-Za-z])" + c + @"(?![A-Za-z])", RegexOptions.IgnoreCase) || n.Contains(Rules.Normalize(Rules.Names[c].En)) || n.Contains(Rules.Names[c].Zh) || c == "WA" && n.Contains("西澳") || c == "VIC" && n.Contains("维州") || c == "NSW" && n.Contains("新州")).ToArray(); var visa = Regex.Match(text, @"\b(190|491)\b").Value; var year = Regex.Match(text, @"\b\d{4}-\d{2}\b").Value; var intent = n.Contains("配额") || n.Contains("allocation") ? "allocation" : "occupation_history"; var missing = new List<string>(); if (states.Length != 1) missing.Add("state"); if (visa == "") missing.Add("visaSubclass"); if (year == "" || !Rules.ValidYear(year)) missing.Add("programYear"); if (intent != "allocation" && candidates.Count != 1) missing.Add("occupationCodeAndVersion"); return await Wrap(new Interpretation(intent, candidates, states, visa == "" ? null : visa, year == "" ? null : year, missing.Count > 0, missing), r, "interpretation_only", "Rules-based interpretation; confirm candidates and filters before requesting an answer.");
    }
    public async Task<Envelope<AnswerData>> Answer(AnswerRequest a) { if (!a.Confirmed) throw new ApiFailure(422, "CONFIRMATION_REQUIRED", "Confirm occupation and scope before answering"); if (string.IsNullOrWhiteSpace(a.Question) || a.Question.Length > 1200) throw new ApiFailure(400, "INVALID_QUESTION", "Question length must be 1–1200"); State(a.State); var r = await Select(new(a.Mode, a.ProgramYear, a.VisaSubclass, "state", a.Locale, a.DatasetVersion)); if (a.OccupationId is not null && !(await Catalog()).Any(o => o.Id == a.OccupationId)) throw new ApiFailure(404, "OCCUPATION_NOT_FOUND", "Occupation must be a confirmed catalog candidate"); var facts = await Facts(r, a.State, a.ProgramYear, a.VisaSubclass, a.OccupationId); if (a.OccupationId is null) facts = facts.Where(f => f.MetricType == "nomination_allocation").ToList(); var summary = a.Locale == "zh" ? facts.Count == 0 ? "当前数据版本没有该范围的已录入历史记录。缺失不等于零。" : $"找到 {facts.Count} 条历史观测。请逐项核对指标、时间范围和来源；不同指标不作合并。" : facts.Count == 0 ? "No ingested history for this scope. Missing does not mean zero." : $"Found {facts.Count} observations. Metrics and periods remain separate."; return await Wrap(new AnswerData("template", summary, facts, ["历史末位 EOI 分数不保证获邀；不估算个人概率。", "未录入职业轮次、政策或人数时，不从配额推断。", "无需 Gemini 密钥；此版本未接入外部语言模型。"], facts.Count == 0 ? ["historicalEvidence"] : []), r); }
}
