using System.Security.Cryptography;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
namespace Atlas;

public static class Seed
{
    static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public static async Task Run(AtlasDb db, string root)
    {
        await db.Database.MigrateAsync();
        if ((await db.Database.SqlQueryRaw<int>("SELECT count(*)::int AS \"Value\" FROM dataset_version WHERE status='published'").SingleAsync()) == 3) return;
        if ((await db.Database.SqlQueryRaw<int>("SELECT count(*)::int AS \"Value\" FROM dataset_version").SingleAsync()) != 0) throw new InvalidOperationException("Partial seed requires review; refusing to modify a published release.");
        var manifest = JsonDocument.Parse(await File.ReadAllTextAsync(Path.Combine(root, "verified/manifest.json"))).RootElement;
        var bytes = await File.ReadAllBytesAsync(Path.Combine(root, "verified/allocation-table.html"));
        if (Convert.ToHexStringLower(SHA256.HashData(bytes)) != manifest.GetProperty("hash").GetString()) throw new InvalidOperationException("Official snapshot hash mismatch");
        var table = System.Text.Encoding.UTF8.GetString(bytes);
    var contextBytes=await File.ReadAllBytesAsync(Path.Combine(root,"verified/decision-context.html"));
    if(Convert.ToHexStringLower(SHA256.HashData(contextBytes))!=manifest.GetProperty("decisionContextHash").GetString())throw new InvalidOperationException("Decision context hash mismatch");
        var cells = manifest.GetProperty("allocations").EnumerateArray().ToArray();
        if (cells.Length != 16 || cells.Select(x => x.GetProperty("state").GetString() + x.GetProperty("subclass").GetString()).Distinct().Count() != 16) throw new InvalidOperationException("Incomplete allocation manifest");
        var sourceRows = Regex.Matches(table, @"<tr[^>]*>(.*?)</tr>", RegexOptions.Singleline | RegexOptions.IgnoreCase).Select(row => Regex.Matches(row.Groups[1].Value, @"<td[^>]*>(.*?)</td>", RegexOptions.Singleline).Select(cell => Regex.Replace(System.Net.WebUtility.HtmlDecode(Regex.Replace(cell.Groups[1].Value, @"<[^>]+>", "")), @"[\s\p{Cf}]", "")).ToArray()).Where(row => row.Length == 3 && Rules.StateCodes.Contains(row[0])).ToDictionary(row => row[0]);
        foreach (var state in Rules.StateCodes) { if (!sourceRows.TryGetValue(state, out var row)) throw new InvalidOperationException("Missing official row " + state); foreach (var cell in cells.Where(x => x.GetProperty("state").GetString() == state)) { var index = cell.GetProperty("subclass").GetString() == "190" ? 1 : 2; if (cell.GetProperty("value").GetInt32() != int.Parse(row[index].Replace(",", ""))) throw new InvalidOperationException("Manifest cell differs from source"); } }
        await using var transaction = await db.Database.BeginTransactionAsync();
        async Task Add(string tableName, object row)
        {
            if (tableName is not ("jurisdiction" or "dataset_version" or "source_version" or "dataset_source" or "program_scope" or "observation_revision" or "dataset_observation" or "occupation" or "distribution" or "distribution_bin" or "publication_audit")) throw new InvalidOperationException("Seed table not allowed");
#pragma warning disable EF1002 // Table identifier is restricted to the internal allow-list above; every value is a parameter.
            await db.Database.ExecuteSqlRawAsync($"INSERT INTO {tableName} SELECT * FROM jsonb_populate_record(NULL::{tableName},{{0}}::jsonb)", JsonSerializer.Serialize(row, Json));
#pragma warning restore EF1002
        }
        var official = Rules.Id("official-allocations-source"); var source1 = Rules.Id("demo-source-v1"); var source2 = Rules.Id("demo-source-v2");
        foreach (var code in Rules.StateCodes) await Add("jurisdiction", new { code, name_en = Rules.Names[code].En, name_zh = Rules.Names[code].Zh });
        foreach (var (key, mode, parent) in new[] { ("verified-2025-26-v1", "verified_historical", (string?)null), ("demo-v1", "demo", (string?)null), ("demo-v2", "demo", (string?)"demo-v1") }) await Add("dataset_version", new { key, mode, status = "draft", published_at = "2026-10-08T00:00:00Z", supersedes_key = parent, note = mode == "demo" ? "Synthetic examples for behavior verification" : "16 official allocation cells only; occupation rounds and policies not ingested" });
        await Add("source_version", new { id = official, source_id = "homeaffairs-allocations", title = manifest.GetProperty("title").GetString(), publisher = "Australian Department of Home Affairs", url = manifest.GetProperty("url").GetString(), terms_url = "https://www.homeaffairs.gov.au/access-and-accountability/using-our-website/copyright-and-disclaimer", license = "CC BY 3.0 Australia; retained table only, excluding logos and third-party material", hash = manifest.GetProperty("hash").GetString(), retrieved_at = manifest.GetProperty("retrievedAt").GetString(), published_at = (string?)null, effective_date = manifest.GetProperty("effectiveDate").GetString(), decision_date=manifest.GetProperty("decisionDate").GetString(), storage_key = "data/verified/allocation-table.html", review_note = "Publication timestamp and effective date not stated; the allocation-setting decision date is separately recorded. This is nomination allocation, not invitations or grants.", is_demo = false });
        foreach (var v in new[] { 1, 2 }) { var raw = await File.ReadAllTextAsync(Path.Combine(root, $"demo/fixture-v{v}.json")); await Add("source_version", new { id = v == 1 ? source1 : source2, source_id = "synthetic-fixture", title = $"Synthetic fixture v{v} — not official data", publisher = "Nomination Atlas demo", url = (string?)null, terms_url = (string?)null, license = "CC0 synthetic fixture", hash = Rules.Hash(raw), retrieved_at = "2026-10-08T00:00:00Z", published_at = "2026-10-08T00:00:00Z", effective_date = (string?)null, storage_key = $"data/demo/fixture-v{v}.json", review_note = "Fabricated occupations, rounds and distributions for application testing; no prediction or migration advice.", is_demo = true }); }
        await Add("dataset_source", new { version = "verified-2025-26-v1", source_version_id = official });
        await Add("dataset_source", new { version = "demo-v1", source_version_id = source1 });
        await Add("dataset_source", new { version = "demo-v2", source_version_id = source1 });
        await Add("dataset_source", new { version = "demo-v2", source_version_id = source2 });
        var scopes = new HashSet<string>();
        async Task<string> Scope(string state, string visa, string year, string? round, string basis = "as_published", string? date = null) { var id = Rules.Id($"{state}:{visa}:{year}:{round}:{basis}"); if (scopes.Add(id)) await Add("program_scope", new { id, state, visa_subclass = visa, sponsorship_type = "state", program_year = year, stream = round is null ? "all" : "demo-general", residence_category = round is null ? "all" : "WA", points_basis = basis, classification_version = "2022", round_id = round, event_date = date }); return id; }
        async Task<string> Fact(string canonical, string scope, string? occupation, string metric, decimal? value, string source, string locator, bool demo, int revision = 1, string? date = null, string? start = null, string? end = null, string? eoi = null, string status = "available", string? reason = null) { Rules.ValueAllowed(metric, value, status, reason); var id = Rules.Id(canonical + ":" + revision); await Add("observation_revision", new { id, canonical_key = canonical, revision, scope_id = scope, occupation_id = occupation, metric_type = metric, value, unit = metric == "last_invited_eoi_points" ? "points" : "count", status, null_reason = reason, event_date = date, period_start = start, period_end = end, as_of_date = (string?)null, eoi_effective_at = eoi, source_version_id = source, locator, is_demo = demo }); return id; }
        async Task Member(string version, string id) => await Add("dataset_observation", new { version, observation_id = id });
        foreach (var cell in cells) { var state = cell.GetProperty("state").GetString()!; var visa = cell.GetProperty("subclass").GetString()!; var scope = await Scope(state, visa, "2025-26", null, "not_applicable"); var id = await Fact($"allocation:{state}:{visa}:2025-26", scope, null, "nomination_allocation", cell.GetProperty("value").GetInt32(), official, cell.GetProperty("locator").GetString()!, false, start: "2025-07-01", end: "2026-06-30"); await Member("verified-2025-26-v1", id); }
        var fixture = JsonDocument.Parse(await File.ReadAllTextAsync(Path.Combine(root, "demo/fixture-v1.json"))).RootElement;
        var occupations = fixture.GetProperty("occupations").EnumerateArray().ToArray();
        foreach (var o in occupations) await Add("occupation", new { id = Rules.Id(o.GetProperty("code").GetString()!), system = "ANZSCO", version = "2022", code = o.GetProperty("code").GetString(), title = o.GetProperty("title").GetString(), title_zh = o.GetProperty("titleZh").GetString() });
        var wa = await Scope("WA", "190", "2025-26", "demo-round-2026-05-20", date: "2026-05-20");
        foreach (var o in occupations) { var code = o.GetProperty("code").GetString()!; var occ = Rules.Id(code); foreach (var metric in new[] { "last_invited_eoi_points", "nomination_invitation_count" }) { decimal? value = metric == "last_invited_eoi_points" ? o.GetProperty("points").GetDecimal() : o.GetProperty("count").ValueKind == JsonValueKind.Null ? null : o.GetProperty("count").GetDecimal(); var id = await Fact($"WA:{code}:{metric}:2026-05-20", wa, occ, metric, value, source1, $"occupations[code={code}].{(metric == "last_invited_eoi_points" ? "points" : "count")}", true, date: "2026-05-20", eoi: "2026-04-20T08:00:00Z", status: value is null ? "suppressed" : "available", reason: value is null ? "small_sample_suppressed" : null); await Member("demo-v1", id); if (code == "261313" && metric == "nomination_invitation_count") { var updated = await Fact($"WA:{code}:{metric}:2026-05-20", wa, occ, metric, 40, source2, "occupations[code=261313].count; correction", true, 2, date: "2026-05-20", eoi: "2026-04-20T08:00:00Z"); await Member("demo-v2", updated); } else await Member("demo-v2", id); } }
        foreach (var state in new[] { "NSW", "VIC" }) { var scope = await Scope(state, "190", "2025-26", "demo-round-2026-05-20", date: "2026-05-20"); foreach (var (o, i) in occupations.Take(3).Select((o, i) => (o, i))) { var code = o.GetProperty("code").GetString()!; var id = await Fact($"{state}:{code}:points", scope, Rules.Id(code), "last_invited_eoi_points", 80 + i * 5, source1, $"additionalStateScores.{state}[{i}]", true, date: "2026-05-20"); await Member("demo-v1", id); await Member("demo-v2", id); } }
        foreach (var (year, value, end) in new[] { ("2023-24", 210, "2024-06-30"), ("2024-25", 310, "2025-06-30"), ("2025-26", 280, "2026-06-30"), ("2026-27", 62, "2026-10-08") }) { var scope = await Scope("WA", "190", year, null, "not_applicable"); var id = await Fact($"annual:{year}:software", scope, Rules.Id("261313"), "nomination_invitation_count", value, source1, $"annual[{(year == "2026-27" ? "2026-27YTD" : year)}]", true, start: year[..4] + "-07-01", end: end); await Member("demo-v1", id); await Member("demo-v2", id); }
        foreach (var version in new[] { "demo-v1", "demo-v2" }) foreach (var (code, kind, n, bins) in new (string, string, long?, (decimal, long?, string)[])[] { ("261313", "published_sample", 100, [(65, 12, "available"), (70, 23, "available"), (75, 40, "available"), (80, 25, "available")]), ("261312", "published_sample", null, [(75, 8, "available")]), ("334111", "published_sample", null, [(65, 12, "available"), (70, null, "suppressed")]), ("333411", "last_invited", null, []) }) { var id = Rules.Id($"dist:{version}:{code}"); await Add("distribution", new { id, version, scope_id = wa, occupation_id = Rules.Id(code), source_version_id = source1, metric_type = "visa_invitation_count", cohort_kind = kind, denominator = n, definition = "Synthetic published sample; separate from nomination counts", locator = $"distributions[{code}]" }); foreach (var (lower, count, status) in bins) await Add("distribution_bin", new { id = Rules.Id(id + lower), distribution_id = id, lower, upper = lower, lower_inclusive = true, upper_inclusive = true, count, status }); }
        foreach (var version in new[] { "verified-2025-26-v1", "demo-v1", "demo-v2" }) { await Add("publication_audit", new { id = Rules.Id("publish:" + version), version, at = "2026-10-08T00:00:00Z", actor = "reviewed-local-seed", reason = "Validated snapshot and synthetic fixtures; immutable publication" }); await db.Database.ExecuteSqlInterpolatedAsync($"UPDATE dataset_version SET status='published' WHERE key={version}"); }
        await db.Database.ExecuteSqlRawAsync("CREATE ROLE atlas_reader NOLOGIN; GRANT USAGE ON SCHEMA public TO atlas_reader; GRANT SELECT ON ALL TABLES IN SCHEMA public TO atlas_reader; ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO atlas_reader");
        await transaction.CommitAsync();
    }
}
